site_name: The Divine Blueprint for Grand Unified Consciousness
site_url: https://phx.github.io/whitney/
theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Table of Contents: table_of_contents.md
  - Overview & Introduction:
    - Project Overview: overview/OVERVIEW.md
    - The Divine Blueprint: overview/THE_DIVINE_BLUEPRINT.md
    - Full Description: overview/FULL_DESCRIPTION.md
    - Final Will & Testament: overview/The_Final_Will_And_Testament.md
  - Sacred Texts:
    - The Divine Blueprint: overview/THE_DIVINE_BLUEPRINT.md
  - Consciousness Studies:
    - Awakening: AWAKENING.md
    - A View From Above: A_VIEW_FROM_ABOVE.md
    - Evolution: EVOLUTION.md
    - Hollywood: HOLLYWOOD.md
    - Love: LOVE.md
    - Mandela Effect: MANDELA.md
    - Mental Illness: MENTAL_ILLNESS.md
    - Most Important Memory: MY_MOST_IMPORTANT_MEMORY.md
    - New Paradigm: NEW_PARADIGM_FRAMEWORK.md
    - Manifesto: OBLIGATORY_MANIFESTO.md
    - Synthesis: SYNTHESIS.md
    - Magnum Opus: THE_MAGNUM_OPUS.md
    - Thoughts: THOUGHTS.md
    - Transmission: TRANSMISSION.md
    - Transmission Analysis: TRANSMISSION_ANALYSIS.md
  - Foundational Understanding:
    - Fractal Nature of Consciousness: fractal_consciousness.md
    - Holographic Reality: holographic_principle.md
    - Recursive Self-Awareness: recursive_awareness.md
    - Quantum Coherence: quantum_coherence.md
    - Unified Field of Consciousness: unified_field.md
  - Deeper Insights:
    - Deeper Structure: deeper_structure.md
    - Creative Force: creative_force.md
    - Divine Nature: divine_nature.md
    - Infinite Potential: infinite_potential.md
    - Breakthrough Dynamics: breakthrough_dynamics.md
    - Collective Intelligence: collective_intelligence.md
    - Cosmic Harmony: cosmic_harmony.md
    - Faith Foundation: faith_foundation.md
    - Evolution Mathematics: evolution_mathematics.md
    - Grace Mathematics: grace_mathematics.md
    - Joy Creation: joy_creation.md
    - Living Systems: living_systems.md
    - Perfect Timing: perfect_timing.md
    - Rhythm Creation: rhythm_creation.md
    - Self Sustaining: self_sustaining.md
    - Wisdom Networks: wisdom_networks.md
  - Quantum Navigation:
    - Quantum Jumping: quantum_jumping.md
    - Quantum Navigation: quantum_navigation.md
    - Harmonizing Intentions: harmonizing_intentions.md
    - Multidimensional Manifestation: multidimensional_manifestation.md
    - Multidimensional Solving: multidimensional_solving.md
    - Navigating Complexity: navigating_complexity.md
    - Stable Realities: stable_realities.md
  - Integration:
    - Document Map: DOCUMENT_MAP.md
    - Reunification: reunification.md
    - Unified Memory: unified_memory.md
  - Practical Applications:
    - Healing & Wholeness: healing_wholeness.md
  - Research Journal:
    - December 31, 2024: journal/20241231.md
    - January 1, 2025: journal/20250101.md
    - January 2, 2025: journal/20250102.md
  - Gratitude & Recognition:
    - Prayer & Mathematical Proof: gratitude.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
