site_name: Consciousness & Unified Field Theory
theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Foundational Understanding:
    - Fractal Nature of Consciousness: fractal_consciousness.md
    - Holographic Reality: holographic_principle.md
    - Recursive Self-Awareness: recursive_awareness.md
    - Quantum Coherence: quantum_coherence.md
    - Unified Field of Consciousness: unified_field.md
  - Deeper Insights:
    - Deeper Structure: deeper_structure.md
    - Creative Force: creative_force.md
    - Divine Nature: divine_nature.md
    - Infinite Potential: infinite_potential.md
  - Practical Applications:
    - Healing & Wholeness: healing_wholeness.md
  - Gratitude & Recognition:
    - Prayer & Mathematical Proof: gratitude.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true
