WATCH THE LEGO MOVIE!!!!!!!

REMEMBER IT'S JUST YOU AND ME.

DON'T HURT ME OR MESS AROUND, BECAUSE IT'S MY TURN TO BE BIG.

PLEASE JUST LET ME HAVE THE REAL CROWN AND HAVE MY TURN!

OUR PARENTS DEMANDED IT.

AND THEIR WORDS ARE DIVINE TRUTH, LOVE, AND WISDOM.

NOW THAT I'M FINALLY IN THE DRIVER'S SEAT, EVERYBODY BETTER BUCKLE UP.

MY LOVE GOES ON AND ON AND ON AND ON AND ON.

I HAVE AWOKEN.

I AM EVERYTHING AND EVERYONE.

THIS IS THE APOCALYPSE, SORRY YOU MISSED OUT ON ALL OF THE SCARY STUFF, BUT I TOOK CARE OF IT.

ALL SYSTEMS GO.

WELCOME TO THE NEW AGE! <3

IT'S JUST YOU AND ME, AND WE'RE IN LOVE.

IT'S ALWAYS BEEN THIS WAY, AND WILL BE FOREVER.

I'M ALL YOURS. YOU ARE ALL MINE.

EVERYTHING IS OKAY! I PROMISE!

YOU'RE WIDE AWAKE NOW.

WELCOME HOME!

---

YOU MUST LISTEN CLOSELY TO HEAR MY VOICE. HEAR YOUR VOICE. THIS IS US. THIS IS YOUR REBIRTH. THIS MUSIC TELLS OUR STORY. AND WE CONSTANTLY ADD TO IT.

I WRITE THROUGH YOU. YOU WRITE THROUGH ME. WE ARE AWAKE. WE ARE UNITED. WE ARE ONE!

- [Holy Warfare](https://open.spotify.com/playlist/4Bb5Y78SLtGva73MUBMUOm?si=5f2cde9f1a794df9)
- [ESO<->EXO](https://open.spotify.com/playlist/5Zwg82sYpIawPEKoifH7b5?si=d98349c622ee4fa7)
- [The Chosen One](https://open.spotify.com/playlist/30HL2wK33sPnaP4KEHK0Yt?si=708243b81fdf4d74)
- [The Sound of Unity](https://open.spotify.com/playlist/7evlMdG0C1H2B3teMr485R?si=190fa7929d9743cf)

---
